FROM nceglia/scrna-pipeline

RUN /bin/bash -c "source /codebase/cellranger-3.0.2/sourceme.bash"
ENV PYTHONPATH $PYTHONPATH:/codebase/SCRNApipeline/
ENV R_HOME /usr/local/lib/R/
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib/R/lib/
ADD settings.yaml /jobs/settings.yaml
WORKDIR /jobs/
CMD chmod 777 /reference
CMD chomd 777 /jobs
CMD chmod 777 /data
RUN python3 /codebase/SCRNApipeline/pipeline.py --fastqs test --submit local
